std::string SkillIDs[395] = {
        "Aura Particle",
        "Psycho Wave",
        "Psycho Burst",
        "Psycho Knife",
        "Psycho Blade",
        "Excalibur",
        "Laser Blade",
        "Mist Blade",
        "Lightning Sword",
        "Ice Sword",
        "Flame Sword",
        "Blazing Sword",
        "Vacuum Slash",
        "Empty Hand",
        "High-speed Punch",
        "Dragon Punch",
        "Tiger Kick",
        "Leg Throw",
        "Hyperkick",
        "Hyperpunch",
        "Dance of Death",
        "Sky Pursuit",
        "Pursuit",
        "Splashdown",
        "Aura Leak",
        "Aura Backflow",
        "Dhampir Claw",
        "Dhampir Fang",
        "Song of Succubus",
        "Succubus Tempt",
        "Muramasa Blade",
        "Bomb",
        "Big Bomb",
        "Cluster Bomb",
        "Psycho Sniper",
        "Debris Bullet",
        "Throwing Stone",
        "Stone Shot",
        "Rock Shot",
        "Rail Gun",
        "Psycho Spear",
        "Psycho Kinesis",
        "Laser",
        "Slide Laser",
        "Mist Laser",
        "Double Laser",
        "Auto Shell",
        "Mist Blaster",
        "Rapid Cannon",
        "Charged Particle",
        "Ricochet Laser",
        "Vibration Laser",
        "Trench Mortar",
        "Blaster",
        "Vibration Blaster",
        "Bundled Laser",
        "Bundled Blaster",
        "Gungnir",
        "Finisher",
        "Sonic Boom",
        "Ice Lance",
        "Bullet of Fire",
        "Blazing Bullet",
        "Lightning Blade",
        "Storm Blade",
        "Root of Tree",
        "Fang of Tree",
        "Scar of Battles",
        "Memory of Battle",
        "Snap",
        "Ki Bullet",
        "Hyper Ki Bullet",
        "Ki Lance",
        "Hyper Ki Lance",
        "Ki Cannon",
        "Scream of Evil",
        "Lucifer's Arrow",
        "Judge of Anubis",
        "Greedy Spirit",
        "Swarm of Moths",
        "Arrow of Artemis",
        "Fire of Gehenna",
        "Venom Fang",
        "Crawlers",
        "Demon's Fire",
        "Seal of Death",
        "Vampire Bat",
        "Hell's Fire",
        "Lingering Flame",
        "Agonies of Death",
        "Frighten",
        "Heat from Void",
        "Meteor",
        "Gravity Press",
        "Massive Quake",
        "Thor's Hammer",
        "Remote Mine",
        "Timer Mine",
        "Rain of Stones",
        "Rain of Rocks",
        "Photon Shower",
        "Killer Satellite",
        "Lightning Bolt",
        "Thunder Storm",
        "Ice Storm",
        "Fire Storm",
        "Blazing Storm",
        "Celestial Ship",
        "Binding Needle",
        "Photon Wave",
        "Photon Burst",
        "Twister",
        "Whirlwind",
        "Recollection",
        "Copy",
        "Crystal Wall",
        "Wall",
        "Psychic Wall",
        "Laser Barrier",
        "Flash Barrier",
        "Paralyze Barrier",
        "Eraser",
        "Photon Barrier",
        "Glacial Wall",
        "Wall of Current",
        "Wall of Fire",
        "Cyclone",
        "Shield of Ruin",
        "Shield of Aegis",
        "Psycho Shell",
        "Laser Shell",
        "Guard of Water",
        "Fortress of Iron",
        "Iron Skin",
        "Mind's Eye",
        "Protect Circle",
        "Guardian Angel",
        "About Face",
        "Reverse",
        "Reflect Barrier",
        "Reflect Mirror",
        "Vacuum Wall",
        "Absorb Energy",
        "Learning",
        "Digestion",
        "Flash Hole",
        "Dark Hole",
        "Bend",
        "Change Course",
        "Gust",
        "Block",
        "Protect",
        "Guard",
        "Devil's Arm",
        "Angel's Wing",
        "Interference",
        "Restrain",
        "Exhaust",
        "Bloody Ritual",
        "Disintegrate",
        "Wind Pressure",
        "Tiger Slayer",
        "Dragon Slayer",
        "Giant Slayer",
        "Lack",
        "Hungry Demon",
        "Turbulence",
        "Calamity",
        "Fairy Ring",
        "Shatter",
        "Confusion Gas",
        "Eliminate",
        "Panic Gas",
        "Evaporate",
        "Abyss",
        "Diabolical Trick",
        "Violent Charge",
        "Particle Convert",
        "Starting Point",
        "Judgement",
        "Neutralization",
        "Angel's Breath",
        "Purify",
        "Freeze Gas",
        "Refresh",
        "Angel Tears",
        "Return to Nature",
        "Desertification",
        "Holy Ray",
        "Lunar Force",
        "Reduce Gravity",
        "Abnormal Gravity",
        "Dense Fog",
        "Backdraft",
        "Optimization",
        "Nature Blessing",
        "Berserk",
        "Forest Sanctuary",
        "Commandments",
        "Fatigue",
        "Soul Cage",
        "Irregular Rhythm",
        "Memory Lapse",
        "Necronomicon",
        "Spore Schism",
        "Athena's Command",
        "Pressure",
        "Lift Up",
        "Paralyze",
        "Entangle",
        "Pin Down",
        "Triple Lasers",
        "Optical Camo",
        "Decoy",
        "Meditation",
        "Friendship",
        "Doze",
        "Curse of Earth",
        "Heat",
        "Stimulate",
        "Tiger's Strength",
        "Trance",
        "Alleviate",
        "Burden",
        "Speed Up",
        "Lightning Speed",
        "Doppelganger",
        "Magnetic Field",
        "Acquisition",
        "Skywalk",
        "Demon's Wing",
        "Frostbite",
        "Brain Concussion",
        "Gravity Mine",
        "Reduce Entropy",
        "Ki Palm",
        "Mind Reading",
        "Armaros",
        "Void",
        "Healing Water",
        "Graceful Woods",
        "Blessed Water",
        "Regenerate",
        "Fusion",
        "Invulnerability",
        "Scientism",
        "Recall",
        "Dazzle",
        "Quiet Days",
        "Call",
        "Retreat",
        "Change the World",
        "Teleportation",
        "Suprise Attack",
        "Levitate",
        "Return",
        "Overheat",
        "Jump",
        "Bravery Decision",
        "Mephisto's Pact",
        "Bomb Shot",
        "Providence",
        "Amulet",
        "Trigger",
        "Annoying Gift",
        "Meltdown",
        "Relearn",
        "Steal Power",
        "Vicious Balance",
        "Level Berserk",
        "Level Amp",
        "Level Boost",
        "Sensor Mine",
        "Power Shell",
        "Power",
        "Vanishing Light",
        "Crush",
        "Confused Gravity",
        "Accelerate",
        "Compressor",
        "Quantum Decay",
        "Octolaser",
        "Orb",
        "Crystallization",
        "Piece of Fire",
        "Piece of Ice",
        "Piece of Thunder",
        "Tremor",
        "Chaos",
        "Stagnant Air",
        "Disrupt",
        "Swift Blow",
        "Swift Kick",
        "Swift Punch",
        "Dash",
        "Spiritual World",
        "Thieving Imp",
        "Reincarnation",
        "Sign of Saints",
        "Demon's Venom",
        "Rebirth",
        "Delay Bomb",
        "Mini-Meteor",
        "Antigravity Trap",
        "Charge",
        "Aura Cannon",
        "Throttle Blaster",
        "Boost Mine",
        "Quantum Amp",
        "Piece of Wind",
        "Throttle Fireball",
        "Tornado",
        "Earthquake",
        "Vacuum Palm",
        "Backdraft Bullet",
        "Lost Dragon",
        "Disremember",
        "True Muramasa",
        "Will-o'-the-Wisp",
        "Jack Pot",
        "Joke of Anubis",
        "Excaliber",
        "Knife Grind",
        "Fast Bomb",
        "Shield Breaker",
        "Fast Wave",
        "Twist Laser",
        "Erase Shell",
        "Level Baton",
        "Arc of Fire",
        "Chill Breeze",
        "Blessed Rain",
        "Unison",
        "Crawling Bullet",
        "Dragon Bullet",
        "Ethos Inspiration",
        "Vacuum Bullet",
        "Dance of Moths",
        "Illusion of Death",
        "Judge of Ares",
        "Armaros Watch",
        "Still Moment",
        "EL Bomb",
        "Life-Giving Sword",
        "Pursuit Stopper",
        "Mobilize",
        "Arms of the Curse",
        "Freeze Shot",
        "Teleportrap",
        "Giga Ruin",
        "Wings of Hope",
        "Cooling",
        "Protecting Air",
        "Geyser Impact",
        "Vast Mayhem",
        "Particle Mortar",
        "Place of Invisibility",
        "Young White Dragon",
        "Dragon Laser",
        "Impact Burst",
        "Play Dead",
        "Downcast",
        "Vapor Cloud",
        "Heat Devil",
        "Rafflesia Fang",
        "Poison Blur",
        "Failing Wall",
        "Tiger Prevails",
        "Martial Arts Scroll",
        "Sword Slap",
        "Withering Curse",
        "Traveling Thought",
        "Dark Protection",
        "Venom Drip",
        "Phantom Dust",
        " ",
        " ",
        " ",
        " ",
        "Unused / Corrupted Skill",
        "Unused / Corrupted Skill",
        "Failing Wall",
        "Tiger Prevails",
        "Martial Arts Scroll",
        "Sword Slap",
        " ",
        "Withering Curse",
        " ",
        "Traveling Thought",
        "Dark Protection",
        "Venom Drip",
        "Phantom Dust",
        "Unused / Corrupted Skill",
        "Unused / Corrupted Skill",
        "Psycho Wave"
};
