"#version 330 core\n"
"layout (location = 0) in vec3 a_pos;\n"
"layout (location = 1) in vec2 a_tex_coord;\n"
"\n"
"out vec2 tex_coord;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"uniform float img_aspect;\n"
"\n"
"void main() {\n"
"    gl_Position = projection * view * model * vec4(a_pos, 1.0);\n"
"\n"
"    // Adjust with the aspect ratio of the current image to prevent stretching\n"
"    gl_Position.x *= img_aspect;\n"
"\n"
"    tex_coord = a_tex_coord;\n"
"}\n"
"\n"
